services:
  webapp:
    image: jordih2o/webex-iotod-bot
    command: ["/app/wait-for-it.sh", "duckling:7151", "--", "python3.7", "/app/main.py"]
    depends_on:
      - db
      - elasticsearch
      - duckling
    network_mode: "host"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: iotod
    network_mode: "host"
    volumes:
      - dbdata_iotod:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    restart: always
    environment:
      - discovery.type=single-node
    network_mode: "host"

  duckling:
    image: mindmeldworkbench/duckling:master
    restart: always
    network_mode: "host"

volumes:
  dbdata_iotod: