services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: iotod
    ports:
      - "5432:5432"
    volumes:
      - dbdata_iotod:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  duckling:
    image: mindmeldworkbench/duckling:master
    restart: always
    ports:
      - "7151:7151"

volumes:
  dbdata_iotod:
